# Generated by Django 4.2 on 2023-04-19 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('foto', models.ImageField(blank=True, upload_to='users/pictures')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('foto', models.ImageField(blank=True, upload_to='users/pictures')),
                ('crp', models.CharField(max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.psychologist'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('observacoes', models.CharField(blank=True, max_length=255)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.patient')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.psychologist')),
            ],
        ),
    ]
